server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  security:
    user:
      name: test@naver.com
      password: 1q2w3e4r!
    oauth2:
      client:
        registration:
          google:
            clientId: 987577011162-e5do843r1ponrr2ro4te5r4gjsv08v36.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            clientId: YB0T0qQI7L922Yclr0oN
            clientSecret: A38X7dq9y2
            scope:
              - email
              - name
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cizjzapltg5k.ap-northeast-2.rds.amazonaws.com:3306/stussy
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml


